WASdev/tool.accelerate.core

liberty-starter-application/build.gradle, liberty-starter-application/src/main/java/com/ibm/liberty/starter/PatternValidation.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologyFinder.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/RepositoryCallInterceptor.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/temp/ServiceFinder.java, liberty-starter-application/src/main/resources/testServices.json, liberty-starter-application/src/main/webapp/index.html, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/PageFunctionTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/EndpointInputValidationTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/TechnologyFinderTest.java, starter-microservice-persistence/src/main/java/com/ibm/liberty/starter/service/persistence/api/v1/ProviderEndpoint.java
Add pattern validation. Replace read line with reader that contains
character limit. Update name to app accelerator.
=> Fix security flaws and update name.

liberty-starter-application/src/main/webapp/css/style.css, liberty-starter-application/src/main/webapp/index.html
Adding a set of links that should be placed on the yellow section of the footer.
TODO: Add actualy URLs
=> fix(footer): added links to yellow bar footer

starter-microservice-websocket/repository/provided-pom.xml
Remove sample from websockets provided-pom groupId
=> Remove sample from websockets provided-pom groupId

common-war.gradle, liberty-starter-application/src/main/webapp/index.html, liberty-starter-application/src/main/webapp/js/logic.js
Increase timeout to 35 seconds and stop the UI status bar from displaying span.
=> Increase server timeout

liberty-starter-application/src/main/webapp/index.html, liberty-starter-application/src/main/webapp/js/logic.js
Fix the verbiage within Step 3 in the black box depending on your selection of deployment (Local/Bluemix). Also, some jQuery magic for when the User changes the app name, we reflect that change within the black box. Thus, updating the "LibertyProject" to whatever the User is calling it.
=> fix(verbiage): updated verbiage on black box

liberty-starter-application/src/main/webapp/index.html
Update build instructions to read mvn install, rather than $maven.
=> Update build instructions to read mvn install, rather than $maven.

liberty-starter-application/skeletons/base/myProject-application/src/main/webapp/WEB-INF/ibm-web-ext.xml, liberty-starter-application/skeletons/base/myProject-deploy/myProject-bluemix/pom.xml, liberty-starter-application/skeletons/base/myProject-deploy/myProject-localServer/pom.xml, liberty-starter-application/skeletons/base/myProject-wlpcfg/pom.xml, liberty-starter-application/src/main/webapp/index.html
Update context to be myLibertyApp.
=> Update context to be myLibertyApp.

liberty-starter-application/src/main/webapp/index.html
=> Add google analytics back in.

liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunLocalPayloadTest.java
Implement test to run the payload and check that the test endpoint is stood up correctly and that the server can be stopped using mvn clean -P stopServer.
=> Test payload run

liberty-starter-application/src/main/webapp/index.html, liberty-starter-application/src/main/webapp/js/logic.js
Add ?src=accelerator to links that go to WASdev.
Send an event when the user moves forwards through application.
Send an event when the user selects download.
Send an event when the user selects extra help on the page, such as the WDT section and links to where their app is running.
=> Update google analytics

liberty-starter-application/src/main/webapp/css/style.css, liberty-starter-application/src/main/webapp/index.html, liberty-starter-application/src/main/webapp/js/logic.js
Update UI so that the install and deployment information on the right of the download page has the code in black boxes and other text in the grey boxes. Add the missing section that tells you where your code is into the Bluemix section.
=> Ui app doc update

starter-microservice-watsonsdk/repository/0.0.1/compile-pom.xml
Update watson sdk dependency version to 2.9.0.
=> Update watson sdk dependency version to 2.9.0.

liberty-starter-application/src/main/resources/services.json, starter-microservice-watsonsdk/build.gradle, starter-microservice-watsonsdk/repository/0.0.2/compile-pom.xml, starter-microservice-watsonsdk/src/main/java/com/ibm/liberty/starter/service/watsonsdk/api/v1/ProviderEndpoint.java, starter-microservice-watsonsdk/src/test/java/com/ibm/liberty/starter/service/watsonsdk/api/v1/it/ProviderTest.java
Change version 0.0.1 back and add in version 0.0.2 with new watson sdk version instead. Update the name of the watson technology type to be
'Watson SDK'.
=> Change version 0.0.1 back and add in version 0.0.2

liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/matchers/FileContainsLines.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/matchers/Retry.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/45)
=> Add better diagnosis message

liberty-starter-application/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/46)
=> Add dependencies to connect and download from Maven Central

liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologyFinder.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/TechnologyProvider.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/temp/ServiceFinder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/47)
=> Remove unnecessary throws and a few other sonarqube complaints

liberty-starter-application/skeletons/base/myProject-wlpcfg/pom.xml, liberty-starter-application/skeletons/specialFiles/pom.xml, liberty-starter-application/src/main/java/com/ibm/liberty/starter/PomModifier.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunnableJarTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/LocalPomModifierTest.java
Add profile to create runnable jar file. Add tests for runnable jar. Add test to RunLocalPayloadTest to check zip file gets created normally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/48)
=> Add profile to create runnable jar file.

liberty-starter-application/skeletons/base/myProject-wlpcfg/pom.xml, liberty-starter-application/skeletons/specialFiles/pom.xml
Move properties back to top level. Change liberty maven plugin from 1.1 to 1.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/49)
=> Change liberty maven plugin from 1.1 to 1.2.

liberty-starter-application/src/main/java/com/ibm/liberty/starter/PomModifier.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/temp/ServiceFinder.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunLocalPayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunnableJarTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadedZip.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/MvnUtils.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ZipConstructorTest.java
SonarQube identified 3 bugs such as null checks and 3 vunerabilities so
these have been removed as well as some minor and quick to fix smells in
those files (such as use of Sysout).
Also remove the duplication that was added in RunnableJarTest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/51)
=> Fix the major issues outlined by SonarQube and remove duplication

README.md, common-war.gradle
Update liberty install configuration for Gradle plugin to pull Liberty from Maven central. This has been successfully testing using the staging pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/60)
=> Update liberty install configuration for Gradle plugin

liberty-starter-application/skeletons/base/myProject-wlpcfg/servers/LibertyProjectServer/server.xml
Update server.xml file to have explanation of where features are configured and how to configure new ones. Fixes issue https://github.com/WASdev/tool.accelerate.core/issues/66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/68)
=> Update server.xml file to add explanation of feature installation

common-war.gradle, liberty-starter-application/skeletons/specialFiles/pom.xml, starter-microservice-microprofile/.gitignore, starter-microservice-microprofile/repository/0.0.1-SNAPSHOT/server-snippet.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/70)
=> Move to16003

liberty-starter-application/src/main/java/com/ibm/liberty/starter/StarterUtil.java, starter-microservice-swagger/src/main/java/com/ibm/liberty/starter/service/swagger/api/v1/ProviderEndpoint.java
Please review and merge this change set related to trailing slash in paths. The additional slash could sometime result in invalid file path. The fix adds a slash only if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/72)
=> Fix a bug related to trailing slash in path

README.md, liberty-starter-application/src/main/resources/services.json, starter-microservice-microprofile/src/main/java/com/ibm/liberty/starter/service/microprofile/api/v1/ProviderEndpoint.java, starter-microservice-microprofile/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-microprofile/src/test/java/com/ibm/liberty/starter/service/microprofile/api/v1/it/TestApplication.java, starter-microservice-persistence/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-rest/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-swagger/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-web/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-websocket/src/main/webapp/WEB-INF/classes/description.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/73)
=> Remove beta tag

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/85)
=> add .idea to ignore

liberty-starter-application/src/main/java/com/ibm/liberty/starter/FeatureInstaller.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/PomModifier.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/StarterUtil.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/88)
=> Remove unnecesary stuff

liberty-starter-application/skeletons/specialFiles/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/95)
=> Add the version to the resources plugin

liberty-starter-application/src/main/webapp/options/swagger/swagger.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/111)
=> Update swagger options to check all requirements when checkbox clicked.

liberty-starter-application/src/main/webapp/options/swagger/swagger.js
Reverts WASdev/tool.accelerate.core#111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/112)
=> Revert "Update swagger options to check all requirements when checkbox clicked."

liberty-starter-application/src/main/webapp/options/swagger/swagger.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/117)
=> Add all checks to the listener and trigger listener when updates happen

liberty-starter-application/src/main/webapp/css/appacc.css, liberty-starter-application/src/main/webapp/includes/download.html
Also switched the label for the name field from span to label
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/119)
=> Add legend to label the radio buttons for the build type

liberty-starter-application/src/main/webapp/includes/download.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/121)
=> Update Bluemix command in UI to include -Pbluemix.

starter-microservice-swagger/repository/0.0.3/provided-pom.xml, starter-microservice-swagger/repository/0.0.3/runtime-pom.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/122)
=> Update versions in runtime and provided pom files.

starter-microservice-watsonsdk/build.gradle, starter-microservice-watsonsdk/repository/0.0.5/compile-pom.xml, starter-microservice-watsonsdk/src/main/java/com/ibm/liberty/starter/service/watsonsdk/api/v1/ProviderEndpoint.java, starter-microservice-watsonsdk/src/test/java/com/ibm/liberty/starter/service/watsonsdk/api/v1/it/ProviderTest.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/127)
=> Update Watson sdk to version 3.5.1

liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/129)
=> Use the same e-mail address as GitHub when private

liberty-starter-application/skeletons/specialFiles/build.gradle, liberty-starter-application/skeletons/specialFiles/pom.xml, liberty-starter-application/skeletons/specialFiles/settings.gradle, liberty-starter-application/src/main/java/com/ibm/liberty/starter/PatternValidation.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInput.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructor.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateArtifactConfigTags.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/maven/AppArtifactConfigCommand.java, liberty-starter-application/src/main/webapp/css/appacc.css, liberty-starter-application/src/main/webapp/includes/download.html, liberty-starter-application/src/main/webapp/js/controllers/appCtrl.js, liberty-starter-application/src/main/webapp/js/services/appacc.js, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/gradle/unit/CreateArtifactConfigTagsTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/maven/unit/AppArtifactConfigCommandTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GradleBuildFilePayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/MavenPomPayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadStructureTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadZip.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructorTest.java, liberty-starter-application/src/test/js/controllers/appCtrlTest.js, liberty-starter-application/src/test/js/services/appaccTest.js
Add configuration for custom artifact id and group id and corresponding unit, integration and UI tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/130)
=> Add app artifact config

liberty-starter-application/src/main/webapp/includes/download.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/133)
=> Remove GitHub button.

liberty-filter-application/src/main/java/com/ibm/liberty/starter/filter/FilterServlet.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/RedirectionTest.java
Update filter to only catch / not e.g. /cheese. This will fix the redirect issues that we are having.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/134)
=> Fix filter

liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/CORSFilter.java
Allow sites hosted in other domains to call the app accelerator REST api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/138)
=> Add cors filter

starter-microservice-microprofile/repository/0.0.3/provided-pom.xml, starter-microservice-microprofile/repository/0.0.3/runtime-pom.xml, starter-microservice-microprofile/repository/0.0.3/server-snippet.xml, starter-microservice-microprofile/src/main/java/com/ibm/liberty/starter/service/microprofile/api/v1/ProviderEndpoint.java, starter-microservice-microprofile/src/test/java/com/ibm/liberty/starter/service/microprofile/api/v1/it/TestApplication.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/155)
=> Update microprofile feature

starter-microservice-microprofile/build.gradle, starter-microservice-microprofile/repository/0.0.2/provided-pom.xml, starter-microservice-microprofile/repository/0.0.2/runtime-pom.xml, starter-microservice-microprofile/repository/0.0.3/server-snippet.xml, starter-microservice-microprofile/src/main/java/com/ibm/liberty/starter/service/microprofile/api/v1/ProviderEndpoint.java, starter-microservice-microprofile/src/test/java/com/ibm/liberty/starter/service/microprofile/api/v1/it/TestApplication.java
Update microprofile dependencies to use microprofile feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/158)
=> Update microprofile dependencies to use microprofile feature

liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructor.java
Signed off by : Adam Pilkington apilkington@uk.ibm.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/169)
=> Fix to stop extra bytes being written to end of index.html

liberty-starter-application/skeletons/specialFiles/build.gradle, liberty-starter-application/skeletons/specialFiles/pom.xml, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInput.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructor.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateRuntimeTags.java, liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/maven/SetRuntimeCommand.java, liberty-starter-application/src/main/webapp/includes/download.html, liberty-starter-application/src/main/webapp/js/controllers/appCtrl.js, liberty-starter-application/src/main/webapp/js/services/appacc.js, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/gradle/unit/CreateRepositoryTagsTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/gradle/unit/CreateRuntimeTagsTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/maven/unit/SetRepositoryCommandTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/build/maven/unit/SetRuntimeCommandTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GitHubRepositoryCreationTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GradleBuildFilePayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/MavenPomPayloadTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunLocalGradlePayloadUsingBetaTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/RunLocalMavenPayloadUsingBetaTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java, liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/177)
=> Issue:4740or176: Allow app accelerator to use Liberty beta image

liberty-starter-application/skeletons/specialFiles/build.gradle, liberty-starter-application/skeletons/specialFiles/pom.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/180)
=> Update cxf test dependency to version 3.1.11.

liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructor.java, starter-microservice-ms-builder/src/main/webapp/sample/Jenkinsfile, starter-microservice-ms-builder/src/main/webapp/sample/manifests/kube.deploy.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/181)
=> Update Jenkinsfile to use Microservice Builder library.

starter-microservice-ms-builder/src/main/webapp/sample/Jenkinsfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/182)
=> Revert Jenkinsfile back to original state.

README.md, liberty-starter-application/src/main/resources/services.json, liberty-starter-application/src/main/webapp/css/appacc.css, liberty-starter-application/src/main/webapp/includes/download.html, liberty-starter-application/src/main/webapp/includes/footer.html, liberty-starter-application/src/main/webapp/js/controllers/appCtrl.js, liberty-starter-application/src/main/webapp/options/swagger/swagger.html, starter-microservice-ms-builder/src/main/webapp/WEB-INF/classes/description.html, starter-microservice-ms-builder/src/main/webapp/sample/Jenkinsfile, starter-microservice-ms-builder/src/test/java/com/ibm/liberty/starter/service/microprofile/api/v1/it/TestApplication.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/185)
=> Update Jenkinsfile to use Microservice Builder library

liberty-starter-application/src/main/webapp/includes/footer.html, starter-microservice-ms-builder/src/main/webapp/sample/manifests/kube.deploy.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/186)
=> Update kube.deploy.yml file to have lowercase names.

liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/EndpointInputValidationTest.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/193)
=> Make validation check call with rest.

liberty-starter-application/src/main/webapp/includes/download.html
resolve issue #200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/202)
=> Fix application url and server location for gradle build

liberty-starter-application/src/main/webapp/includes/download.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/205)
=> Merge development to master

liberty-starter-application/src/main/java/com/ibm/liberty/starter/client/BxCodegenClient.java
The java generator has been renamed to generator-ibm-java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wasdev/tool.accelerate.core/214)
=> Update name of generator
